theme: jekyll-theme-modernist
title: Multitrack Music Transformer
description: ICASSP 2023
show_downloads: false
icons:
  homepage: fa-solid fa-globe-asia
  video: fa-brands fa-youtube
  paper: fa-solid fa-file-pdf
  slides: fa-solid fa-file-pdf
  poster: fa-solid fa-file-pdf
  arxiv: fa-solid fa-archive
  code: fa-brands fa-github
  documentation: fa-solid fa-book
  reviews: fa-solid fa-comments
  demo: fa-solid fa-globe-asia
  link: fa-solid fa-arrow-up-right-from-square
